
<script type="text/javascript" src="{{asset('js/jquery-2.1.4.min.js')}}"></script>
<script type="text/javascript" src="{{asset('js/bootstrap.min.js')}}"></script>
<script type="text/javascript" src="{{asset('vendors/revolution/js/jquery.themepunch.tools.min.js')}}"></script>
<script type="text/javascript" src="{{asset('vendors/revolution/js/jquery.themepunch.revolution.min.js')}}"></script>
<script type="text/javascript" src="{{asset('vendors/revolution/js/extensions/revolution.extension.video.min.js')}}"></script>
<script type="text/javascript" src="{{asset('vendors/revolution/js/extensions/revolution.extension.slideanims.min.js')}}"></script>
<script type="text/javascript" src="{{asset('vendors/revolution/js/extensions/revolution.extension.layeranimation.min.js')}}"></script>
<script type="text/javascript" src="{{asset('vendors/revolution/js/extensions/revolution.extension.navigation.min.js')}}"></script>
<script type="text/javascript" src="{{asset('vendors/revolution/js/extensions/revolution.extension.parallax.min.js')}}"></script>
<script type="text/javascript" src="{{asset('vendors/bootstrap-selector/bootstrap-select.js')}}"></script>
<script type="text/javascript" src="{{asset('vendors/bootatrap-date-time/bootstrap-datetimepicker.min.js')}}"></script>
<script type="text/javascript" src="{{asset('vendors/owl-carousel/owl.carousel.min.js')}}"></script>
<script type="text/javascript" src="{{asset('vendors/isotope/imagesloaded.pkgd.min.js')}}"></script>
<script type="text/javascript" src="{{asset('vendors/isotope/isotope.pkgd.min.js')}}"></script>
<script type="text/javascript" src="{{asset('vendors/countdown/jquery.countdown.js')}}"></script>
<script type="text/javascript" src="{{asset('vendors/js-calender/zabuto_calendar.min.js')}}"></script>
<script type="text/javascript" src="{{asset('js/theme.js')}}"></script>
<script type="text/javascript" src="{{asset('js/navbar.js')}}"></script>
